Release 6.3.0
containers/oci-spec-rs pull request #147
Opened 2023-10-06 18:30 UTC by jsturtevant

I followed the docs at https://github.com/containers/oci-spec-rs/blob/main/release.md.  

In Particular I am interested in the `artifact_type` added in https://github.com/containers/oci-spec-rs/pull/145.  Thanks!

2023-10-07 04:36 UTC, utam0k commented
@saschagrunert I agree with releasing the new version WDYT?

2023-10-09 06:52 UTC, saschagrunert approved these changes
Sounds good to me!

2023-10-09 06:53 UTC, saschagrunert requested changes

2023-10-09 06:53 UTC, saschagrunert commented on Cargo.toml
> +version = "6.3.0"
Should this be 
```suggestion
version = "0.6.3"
```

2023-10-09 06:53 UTC, saschagrunert commented on README.md
> -oci-spec = "0.6.2"
Same here

2023-10-09 06:53 UTC, saschagrunert requested changes

2023-10-09 06:53 UTC, saschagrunert commented on README.md
> +oci-spec = "6.3.0"
```suggestion
oci-spec = "0.6.3"
```

2023-10-09 16:10 UTC, jsturtevant commented on Cargo.toml
> +version = "6.3.0"
oh woops!

2023-10-09 16:16 UTC, jsturtevant commented
closing since dco is messed up with the extra commit. I re-ran the script and it created a new branch

2023-10-09 16:16 UTC, closed without merging