WIP: Add CNCF project governance
containers/oci-spec-rs pull request #244
Opened 2024-10-17 12:55 UTC by saschagrunert

#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:
Adding the required governance for the project to become part of the CNCF.

#### Which issue(s) this PR fixes:

Refers to #240 
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

2024-10-21 08:06 UTC, saschagrunert commented
PTAL @cgwalters @flavio @thomastaylor312 @utam0k @yihuaf @jprendes @Furisto @YJDoc2

2024-10-21 08:39 UTC, YJDoc2 approved these changes
lgtm :+1:
Thanks @saschagrunert !

2024-10-21 12:45 UTC, cgwalters approved these changes

2024-10-22 08:16 UTC, flavio approved these changes
Sorry for being late, LGTM

2024-10-22 08:41 UTC, merged

2024-10-22 08:51 UTC, jprendes requested changes

2024-10-22 08:51 UTC, jprendes commented on SECURITY.md
> +[cncf-oci-spec-rs-security@lists.cncf.io](mailto:cncf-crio-security@lists.cncf.io) list
I assume that these two addresses not matching is linked to the above TODO, right?

2024-10-22 08:51 UTC, jprendes commented on MAINTAINERS.md
> +| Jorge Prendes   | Independent        | @jprendes        | Maintainer              |
```suggestion
| Jorge Prendes   | Microsoft          | @jprendes        | Maintainer              |
```

2024-10-22 08:52 UTC, jprendes commented
Ah! Slightly too late, sorry! 😅
I'll create a PR.

2024-10-22 08:52 UTC, saschagrunert commented
Thank you @jprendes! :pray:

2024-10-22 09:45 UTC, utam0k approved these changes