Add mutable accessors for some important Vec/HashMap fields
containers/oci-spec-rs pull request #87
Opened 2022-01-04 01:30 UTC by cgwalters

Part of https://github.com/containers/oci-spec-rs/issues/86

An obvious operation to support is generating a derived container
image.  Here we want to take some existing data such as the image
manifest and configuration, and append to key fields such as
the image layers, the config diffids and the history.

Another common operation is adding/changing labels.

Having to create a deep-copy of all this data is unfortunate.
I am not very concerned about performance here, but it's also
an ergonomic hit.

Obviously giving raw `&mut` access to fields means that it goes
"behind the back" of the derive builder, and if we ever started
trying to use more advanced things like validation, that wouldn't
work.

Honestly, I am increasingly convinced the builder thing
is just not worth it and it'd be better to have plain structs with
`pub` fields.  But for now, let's allow direct mutation.

2022-01-10 08:44 UTC, saschagrunert requested changes

2022-01-10 08:44 UTC, saschagrunert commented on src/image/manifest.rs
> +    }
We can derive those by using [`MutGetters`](https://docs.rs/getset/latest/getset/derive.MutGetters.html): 

```patch
diff --git a/src/image/config.rs b/src/image/config.rs
index 6d6ec6c46..79aae8cce 100644
--- a/src/image/config.rs
+++ b/src/image/config.rs
@@ -175,11 +175,6 @@ impl ImageConfiguration {
     pub fn to_writer_pretty<W: Write>(&self, writer: &mut W) -> Result<()> {
         to_writer(&self, writer, true)
     }
-
-    /// Access the history mutably.
-    pub fn get_history_mut(&mut self) -> &mut Vec<History> {
-        &mut self.history
-    }
 }
 
 impl Default for ImageConfiguration {
diff --git a/src/image/manifest.rs b/src/image/manifest.rs
index d5b4f291f..71496117b 100644
--- a/src/image/manifest.rs
+++ b/src/image/manifest.rs
@@ -4,7 +4,7 @@ use crate::{
     from_file, from_reader, to_file, to_writer,
 };
 use derive_builder::Builder;
-use getset::{CopyGetters, Getters, Setters};
+use getset::{CopyGetters, Getters, MutGetters, Setters};
 use serde::{Deserialize, Serialize};
 use std::{
     collections::HashMap,
@@ -13,7 +13,17 @@ use std::{
 };
 
 #[derive(
-    Builder, Clone, CopyGetters, Debug, Deserialize, Eq, Getters, Setters, PartialEq, Serialize,
+    Builder,
+    Clone,
+    CopyGetters,
+    Debug,
+    Deserialize,
+    Eq,
+    Getters,
+    MutGetters,
+    Setters,
+    PartialEq,
+    Serialize,
 )]
 #[serde(rename_all = "camelCase")]
 #[builder(
@@ -57,7 +67,7 @@ pub struct ImageManifest {
     /// The final filesystem layout MUST match the result of applying
     /// the layers to an empty directory. The ownership, mode, and other
     /// attributes of the initial empty directory are unspecified.
-    #[getset(get = "pub", set = "pub")]
+    #[getset(get_mut = "pub", get = "pub", set = "pub")]
     layers: Vec<Descriptor>,
     /// This OPTIONAL property contains arbitrary metadata for the image
     /// manifest. This OPTIONAL property MUST use the annotation
@@ -164,11 +174,6 @@ impl ImageManifest {
     pub fn to_writer_pretty<W: Write>(&self, writer: &mut W) -> Result<()> {
         to_writer(&self, writer, true)
     }
-
-    /// Access the image layers mutably.
-    pub fn get_layers_mut(&mut self) -> &mut Vec<Descriptor> {
-        &mut self.layers
-    }
 }
 
 #[cfg(test)]
@@ -245,7 +250,7 @@ mod tests {
         let mut manifest = create_manifest();
         assert_eq!(manifest.layers().len(), 3);
         let layer_copy = manifest.layers()[0].clone();
-        manifest.get_layers_mut().push(layer_copy);
+        manifest.layers_mut().push(layer_copy);
         assert_eq!(manifest.layers().len(), 4);
     }
 ```

2022-01-11 16:41 UTC, cgwalters commented
Ah, thanks.  I looked through the builder crate docs and didn't see that.

OK I adapted your patch, plus a few other bits and have updated this PR.  I didn't yet test it with my code though.

2022-01-12 08:22 UTC, saschagrunert commented on src/image/config.rs
> +}
Do we still need this?

2022-01-12 15:00 UTC, cgwalters commented
OK!  Now tested with https://github.com/ostreedev/ostree-rs-ext/pull/206 and you can see how much saner the code is!

2022-01-12 15:01 UTC, cgwalters commented
I'll reiterate though, I still feel this builder crate thing is just not worth it over having simple structs with `pub` fields.

2022-01-12 16:11 UTC, saschagrunert approved these changes
LGTM

2022-01-12 16:11 UTC, saschagrunert commented
@utam0k PTAL

2022-01-13 13:13 UTC, merged